# Generated by Django 4.0.1 on 2022-01-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_in', models.CharField(max_length=20, verbose_name='姓名')),
                ('time_in', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('account_type_in', models.SmallIntegerField(choices=[(1, '微信'), (2, '支付宝'), (3, '现金'), (4, '银行卡'), (5, '金融')], verbose_name='账户')),
                ('classify_type_in', models.SmallIntegerField(choices=[(1, '工资'), (2, '兼职'), (3, '经营'), (4, '利息'), (5, '奖金'), (6, '加班'), (7, '基金'), (8, '股票'), (9, '债券'), (10, '其他')], verbose_name='类别')),
                ('money_in', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('notes_in', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='BillOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_out', models.CharField(max_length=20, verbose_name='姓名')),
                ('time_out', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('account_type_out', models.SmallIntegerField(choices=[(1, '微信'), (2, '支付宝'), (3, '现金'), (4, '银行卡'), (5, '信用卡')], verbose_name='账户')),
                ('classify_type_out', models.SmallIntegerField(choices=[(1, '餐饮'), (2, '交通'), (3, '购物'), (4, '居家'), (5, '娱乐'), (6, '人情'), (7, '医疗'), (8, '金融'), (9, '其他')], verbose_name='类别')),
                ('money_out', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('notes_out', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='UserImformation',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='姓名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
            ],
        ),
    ]
